In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("https://archive.ics.uci.edu/static/public/14/data.csv")

In [3]:
df = pd.DataFrame(data)
df

,age,menopause,tumor-size,inv-nodes,node-caps,deg-malig,breast,breast-quad,irradiat,Class
0,30-39,premeno,30-34,0-2,no,3,left,left_low,no,no-recurrence-events
1,40-49,premeno,20-24,0-2,no,2,right,right_up,no,no-recurrence-events
2,40-49,premeno,20-24,0-2,no,2,left,left_low,no,no-recurrence-events
3,60-69,ge40,15-19,0-2,no,2,right,left_up,no,no-recurrence-events
4,40-49,premeno,0-4,0-2,no,2,right,right_low,no,no-recurrence-events
...,...,...,...,...,...,...,...,...,...,...
281,30-39,premeno,30-34,0-2,no,2,left,left_up,no,recurrence-events
282,30-39,premeno,20-24,0-2,no,3,left,left_up,yes,recurrence-events
283,60-69,ge40,20-24,0-2,no,1,right,left_up,no,recurrence-events
284,40-49,ge40,30-34,5-Mar,no,3,left,left_low,no,recurrence-events
285,50-59,ge40,30-34,5-Mar,no,3,left,left_low,no,recurrence-events

In [13]:
#melt
columns_to_melt = ['menopause','node-caps','breast','breast-quad','irradiat','Class']


df_melted = df.melt(id_vars=columns_to_melt, var_name='Measurement', value_name='Value')
df_melted

,menopause,node-caps,breast,breast-quad,irradiat,Class,Measurement,Value
0,premeno,no,left,left_low,no,no-recurrence-events,age,30-39
1,premeno,no,right,right_up,no,no-recurrence-events,age,40-49
2,premeno,no,left,left_low,no,no-recurrence-events,age,40-49
3,ge40,no,right,left_up,no,no-recurrence-events,age,60-69
4,premeno,no,right,right_low,no,no-recurrence-events,age,40-49
...,...,...,...,...,...,...,...,...
1139,premeno,no,left,left_up,no,recurrence-events,deg-malig,2
1140,premeno,no,left,left_up,yes,recurrence-events,deg-malig,3
1141,ge40,no,right,left_up,no,recurrence-events,deg-malig,1
1142,ge40,no,left,left_low,no,recurrence-events,deg-malig,3
1143,ge40,no,left,left_low,no,recurrence-events,deg-malig,3

In [17]:
#pivot
df_pivoted = df_melted.pivot_table(index=columns_to_melt, columns=['Measurement'], values=['Value'],aggfunc='first')
df_pivoted.reset_index(inplace=True)

df_pivoted.columns = ['age', 'menopause', 'tumor-size', 'breast', 'Class', 'inv-nodes', 'node-caps', 'deg-malig', 'breast-quad', 'irradiat']


df_pivoted

,age,menopause,tumor-size,breast,Class,inv-nodes,node-caps,deg-malig,breast-quad,irradiat
0,ge40,no,left,central,no,no-recurrence-events,50-59,2,0-2,0-4
1,ge40,no,left,left_low,no,no-recurrence-events,60-69,2,0-2,15-19
2,ge40,no,left,left_low,no,recurrence-events,50-59,2,0-2,35-39
3,ge40,no,left,left_low,yes,no-recurrence-events,60-69,2,0-2,30-34
4,ge40,no,left,left_low,yes,recurrence-events,60-69,2,5-Mar,20-24
...,...,...,...,...,...,...,...,...,...,...
79,premeno,yes,right,left_up,yes,no-recurrence-events,30-39,2,8-Jun,25-29
80,premeno,yes,right,right_up,no,no-recurrence-events,30-39,2,8-Jun,30-34
81,premeno,yes,right,right_up,no,recurrence-events,40-49,3,0-2,30-34
82,premeno,yes,right,right_up,yes,no-recurrence-events,40-49,2,11-Sep,35-39
83,premeno,yes,right,right_up,yes,recurrence-events,40-49,2,5-Mar,20-24

In [18]:
#aggregation
df['deg-malig'].mean()

2.0489510489510487

In [19]:
#iterate
for index, row in df_pivoted.iterrows():
    print(index, row['age'])

0 ge40
1 ge40
2 ge40
3 ge40
4 ge40
5 ge40
6 ge40
7 ge40
8 ge40
9 ge40
10 ge40
11 ge40
12 ge40
13 ge40
14 ge40
15 ge40
16 ge40
17 ge40
18 ge40
19 ge40
20 ge40
21 ge40
22 ge40
23 ge40
24 ge40
25 ge40
26 ge40
27 ge40
28 ge40
29 ge40
30 ge40
31 ge40
32 ge40
33 ge40
34 ge40
35 ge40
36 ge40
37 ge40
38 lt40
39 lt40
40 lt40
41 premeno
42 premeno
43 premeno
44 premeno
45 premeno
46 premeno
47 premeno
48 premeno
49 premeno
50 premeno
51 premeno
52 premeno
53 premeno
54 premeno
55 premeno
56 premeno
57 premeno
58 premeno
59 premeno
60 premeno
61 premeno
62 premeno
63 premeno
64 premeno
65 premeno
66 premeno
67 premeno
68 premeno
69 premeno
70 premeno
71 premeno
72 premeno
73 premeno
74 premeno
75 premeno
76 premeno
77 premeno
78 premeno
79 premeno
80 premeno
81 premeno
82 premeno
83 premeno

In [22]:
#groupby
df.groupby('Class').agg({
    'deg-malig': ['min', 'max','mean','std']
})

                     deg-malig
                           min max      mean       std
Class
no-recurrence-events         1   3  1.905473  0.697151
recurrence-events            1   3  2.388235  0.725293